### ISSUE TITLE
Modify Collectors to write to S3

### ISSUE THREAD

**Issue by rnason** [atlanteansoftware/CloudQuery-Issues#4]

**Comment by dsikes** [comment]
After digging into this further, it was unnecessary for the Collectors themselves to write to S3. The CollectorRuntime is all that needed access to S3. So I did **NOT** add the write to s3 code to the collector base class, but instead included it in the CollectorRuntime lambda function. It conforms to the following structure: Account/Service/Region/Timestamp.json
